[project]
authors = [
    { name = "Limespy" },
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dynamic = [
    "dependencies",
    "optional-dependencies",
]
license = "MIT"
license-files = [
    "LICENSE.txt",
]
name = "limepackage"
requires-python = ">=3.12"
readme = "README.md"
version = "0.1.0"

[project.scripts]
limepackage = 'limepackage._cli:main'


[project.urls]
Homepage = "https://github.com/lime-actions/build-py"
Changelog = "https://github.com/lime-actions/build-py/blob/main/README.md#Changelog"
"Issue Tracker" = "https://github.com/lime-actions/build-py/issues"

[build-system]
requires = [
    "setuptools",
]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "pre-commit >= 4",
    { include-group = "linting" },
    { include-group = "packaging" },
    { include-group = "tox" },
    { include-group = "typing" },
    { include-group = "unittests" },
]

linting = [
    "limedev[linting]",
]
packaging = [
    "limedev[readme]",
]
tox = [
    "tox >= 4.22",
    "tox-uv >= 1.25.0",
]
typing = [
    "limedev[typing-mypy]",
]
unittests = [
    "limedev[unittesting]",
]

[tool.black]
line-length = 80
preview = true
skip-string-normalization = true


[tool.limedev]
full_name = "LimePackage"

[tool.setuptools.dynamic.dependencies]
file = [
    "dependencies/requirements.txt",
]
